---
title: 3.1.1.异常
weight: 31
---
# 异常
Error  Exception 继承 Throwable 

```aidl
try {
    // 一些会抛出异常的方法
} catch(Exception e) {
    // 处理该异常的代码块
}
```

```aidl
try {

} catch (InputMismatchException e) {

} catch (ArithmeticException e) {

}
```

```aidl
try {

} catch (Exception e) {

} catch (Exception2 e) {

} ...(n个catch块)... {

} finally {
    // 最终将要执行的一些代码
}
```

